### ISSUE TITLE
Blue Pencil

### ISSUE THREAD

**Issue by miguel-botelho** [dimamo5/PLOG-Morelli#2]
As seen here: http://prntscr.com/93uw9o
As everyone can see, dimamo5 _BLUE PENCIL_ coderdudo. However, coderdudo noticed it, and decided to do a commit where he commits _BLUE PENCIL_ to the repository _BLUE PENCIL_ *

**Comment by sceptross** [comment]
Kekei demais com isto xD

**Comment by F0lha** [comment]
The developer closed the issue without even adressing the hardworking and source code loving code monkey and master coder tomislaaaav. I leave a question to coderdudo hoping for a quick and honest answer and with that answer we will trully see who is this enigmatic coderdudo... Why u mad? 8)

**Comment by sergio-domingues** [comment]
http://bit.ly/1kCOc5J  Blue Pencil strikes again.

**Comment by afonsocastro96** [comment]
I am not on good terms with this.

**Comment by miguel-botelho** [comment]
Grândola, Vila Morena...
Terra da, fraternidade...
O povo é quem mais ordenaaaa,
Dentro de ti, ó cidade.

Dentro de ti, ó cidade!
O povo é quem mais ordena.
Terra da fraternidade,
Grândola!, Vila Morena...
